/**
 * Crate digger list: 700+ rare vinyl albums/artists from Sample Roll reference.
 * Builds YouTube search queries with same exclusions as main search (no covers, live, remix, etc.).
 * Loads data at runtime so the build does not require data/crate-digger-list.json.
 */

import path from "path"
import fs from "fs"
import { NEGATIVE_KEYWORDS } from "./youtube-config"

export interface CrateDiggerEntry {
  artist: string
  album: string
  year?: number
  category?: string
}

// Load parsed list at runtime (generated by scripts/parse-crate-digger-pdf.ts from data/crate-digger-list-raw.txt)
let ENTRIES: CrateDiggerEntry[] = []
let loaded = false

function loadEntries(): CrateDiggerEntry[] {
  if (loaded) return ENTRIES
  loaded = true
  try {
    const p = path.join(process.cwd(), "data", "crate-digger-list.json")
    if (fs.existsSync(p)) {
      const raw = fs.readFileSync(p, "utf-8")
      ENTRIES = JSON.parse(raw) as CrateDiggerEntry[]
    }
  } catch {
    // optional: file not committed or missing
  }
  return ENTRIES
}

const negativeKw = NEGATIVE_KEYWORDS.join(" ")

/**
 * Build a single YouTube search query for one crate digger entry.
 * Format: "Artist" "Album" "full album" "vinyl" + NEGATIVE_KEYWORDS
 */
export function buildCrateDiggerQuery(entry: CrateDiggerEntry): string {
  const artist = entry.artist.trim().replace(/\s+/g, " ")
  const album = entry.album.trim().replace(/\s+/g, " ")
  return `"${artist}" "${album}" "full album" "vinyl" ${negativeKw}`
}

/**
 * All search queries (one per entry). Used for playlist discovery or batch use.
 */
export function getCrateDiggerSearchQueries(): string[] {
  return loadEntries().map(buildCrateDiggerQuery)
}

/** Fallback query when the crate digger list is empty (e.g. data file not deployed). */
const FALLBACK_QUERY = `"rare groove" "full album" "vinyl" ${negativeKw}`

/**
 * Pick one random crate digger query for the dig flow.
 */
export function getRandomCrateDiggerQuery(): string {
  const entries = loadEntries()
  if (entries.length === 0) return FALLBACK_QUERY
  const idx = Math.floor(Math.random() * entries.length)
  return buildCrateDiggerQuery(entries[idx])
}

/**
 * Number of entries in the list.
 */
export function getCrateDiggerEntryCount(): number {
  return loadEntries().length
}

/**
 * Playlist-discovery style queries (no negative keywords): "Artist Album full album".
 * Returns a subset (e.g. every 5th entry) to avoid blowing the playlist search budget.
 */
export function getCrateDiggerPlaylistQueries(maxQueries = 120): string[] {
  const entries = loadEntries()
  const step = Math.max(1, Math.floor(entries.length / maxQueries))
  const out: string[] = []
  for (let i = 0; i < entries.length && out.length < maxQueries; i += step) {
    const e = entries[i]
    const artist = e.artist.trim().replace(/\s+/g, " ")
    const album = e.album.trim().replace(/\s+/g, " ")
    out.push(`"${artist}" "${album}" full album`)
  }
  return out
}
