/**
 * Crate digger song list: ~2000 songs derived from the crate digger albums (MusicBrainz).
 * Builds YouTube search queries for song-level discovery (artist + song + vinyl).
 */

import { NEGATIVE_KEYWORDS } from "./youtube-config"

export interface CrateDiggerSongEntry {
  artist: string
  album: string
  song: string
  year?: number
}

// Load song list (generated by scripts/build-crate-digger-songs.ts from crate-digger-list.json)
import crateDiggerSongs from "@/data/crate-digger-songs.json"

const SONG_ENTRIES = crateDiggerSongs as CrateDiggerSongEntry[]
const negativeKw = NEGATIVE_KEYWORDS.join(" ")

/**
 * Build a single YouTube search query for one song entry.
 * Format: "Artist" "Song" "vinyl" + NEGATIVE_KEYWORDS (no "full album" for single-track intent).
 */
export function buildCrateDiggerSongQuery(entry: CrateDiggerSongEntry): string {
  const artist = entry.artist.trim().replace(/\s+/g, " ")
  const song = entry.song.trim().replace(/\s+/g, " ")
  return `"${artist}" "${song}" vinyl ${negativeKw}`
}

/**
 * All search queries (one per song). Used for batch populate or discovery.
 */
export function getCrateDiggerSongQueries(): string[] {
  return SONG_ENTRIES.map(buildCrateDiggerSongQuery)
}

/**
 * Pick one random song query for the dig flow.
 */
export function getRandomCrateDiggerSongQuery(): string {
  if (SONG_ENTRIES.length === 0) return ""
  const idx = Math.floor(Math.random() * SONG_ENTRIES.length)
  return buildCrateDiggerSongQuery(SONG_ENTRIES[idx])
}

/**
 * Number of song entries in the list.
 */
export function getCrateDiggerSongCount(): number {
  return SONG_ENTRIES.length
}
