/**
 * Scan every Sample's current YouTube description (video "bio") for Suno / AI mentions.
 * Writes a markdown report for manual review.
 *
 * Usage: npx tsx scripts/scan-bio-suno-ai.ts [--out path/to/file.md]
 *
 * Env: DATABASE_URL, YouTube API key(s) (same as other scripts).
 *
 * Matching (description only, not title):
 * - Suno: "sunoai", "#suno…", or whole-word "suno" (avoids Italian "nessuno" containing "suno").
 * - AI: "artificial intelligence", ai-generated phrasing, #aimusic, or whole-word ai / a.i.
 *   after stripping URLs and *.ai hostnames (avoids beacons.ai, lalal.ai, etc.).
 */

import "dotenv/config"
import fs from "fs"
import path from "path"
import { prisma } from "@/lib/db"
import { getVideoDetailsFullBatch } from "@/lib/youtube"

const OUT =
  process.argv.find((a) => a.startsWith("--out="))?.slice("--out=".length) ||
  (process.argv.includes("--out") ? process.argv[process.argv.indexOf("--out") + 1] : null) ||
  path.join("reports", "bio-suno-ai-review.md")

const AI_PHRASE = /\bartificial intelligence\b/i
/** Phrases / hashtags that suggest AI-made music or explicit disclosure — not bare "ai" (too many J-pop romaji / French / .ai URLs). */
const AI_MUSICISH =
  /\b(ai-generated|ai generated|generated with ai|generated by ai|made with ai|using ai to (create|make|write|compose|produce))\b|#aimusic|#aigenerated|#\s*sunoai\b|\bsuno\s+ai\b/i

export function mentionsSuno(desc: string): boolean {
  const d = (desc || "").toLowerCase()
  if (d.includes("sunoai")) return true
  if (/#suno\b/i.test(desc)) return true
  return /\bsuno\b/i.test(desc)
}

export function mentionsAi(desc: string): boolean {
  const raw = desc || ""
  if (AI_MUSICISH.test(raw)) return true
  if (!AI_PHRASE.test(raw)) return false
  // "Artificial intelligence" often means video upscale / restoration — skip those lines for this report
  const lower = raw.toLowerCase()
  if (
    /\btopaz\b/.test(lower) ||
    /\bupscal/.test(lower) ||
    /\bdenois/.test(lower) ||
    /\brestored\b.*\bartificial intelligence\b/.test(lower) ||
    /\bartificial intelligence\b.*\b(upscal|1080p|4k|dvd|laserdisc)\b/.test(lower)
  ) {
    return false
  }
  return true
}

export function matchDescriptionBio(desc: string): { suno: boolean; ai: boolean } {
  return { suno: mentionsSuno(desc), ai: mentionsAi(desc) }
}

function excerptAround(text: string, re: RegExp): string {
  const d = text || ""
  const m = re.exec(d)
  if (!m || m.index === undefined) return d.slice(0, 220).replace(/\s+/g, " ").trim() + (d.length > 220 ? "…" : "")
  const start = Math.max(0, m.index - 80)
  const end = Math.min(d.length, m.index + m[0].length + 120)
  let s = d.slice(start, end).replace(/\s+/g, " ").trim()
  if (start > 0) s = "…" + s
  if (end < d.length) s = s + "…"
  return s
}

function excerptForMatch(desc: string, suno: boolean, ai: boolean): string {
  const d = desc || ""
  if (suno) {
    if (/sunoai/i.test(d)) return excerptAround(d, /sunoai/i)
    return excerptAround(d, /\bsuno\b/i)
  }
  if (ai) {
    if (AI_MUSICISH.test(d)) return excerptAround(d, AI_MUSICISH)
    if (AI_PHRASE.test(d)) return excerptAround(d, AI_PHRASE)
  }
  return d.slice(0, 220).replace(/\s+/g, " ").trim() + (d.length > 220 ? "…" : "")
}

async function main() {
  const samples = await prisma.sample.findMany({
    orderBy: { createdAt: "asc" },
    select: { id: true, youtubeId: true, title: true, channel: true },
  })

  const outDir = path.dirname(OUT)
  fs.mkdirSync(outDir, { recursive: true })

  const matches: {
    title: string
    channel: string
    youtubeId: string
    suno: boolean
    ai: boolean
    excerpt: string
  }[] = []

  const batchSize = 50
  for (let i = 0; i < samples.length; i += batchSize) {
    const batch = samples.slice(i, i + batchSize)
    const videoIds = batch.map((s) => s.youtubeId)
    const details = await getVideoDetailsFullBatch(videoIds)

    for (const s of batch) {
      const d = details.get(s.youtubeId)
      const desc = d?.description || ""
      const { suno, ai } = matchDescriptionBio(desc)
      if (!suno && !ai) continue

      matches.push({
        title: s.title,
        channel: s.channel,
        youtubeId: s.youtubeId,
        suno,
        ai,
        excerpt: excerptForMatch(desc, suno, ai),
      })
    }

    if ((i + batchSize) % 200 === 0) {
      console.log(`[scan-bio] ${Math.min(i + batchSize, samples.length)}/${samples.length}…`)
    }
    await new Promise((r) => setTimeout(r, 100))
  }

  const lines: string[] = [
    `# YouTube description scan: Suno / AI`,
    ``,
    `Generated: ${new Date().toISOString()}`,
    ``,
    `- **Total samples scanned:** ${samples.length}`,
    `- **Matches:** ${matches.length}`,
    ``,
    `## Rules`,
    ``,
    `- Descriptions are fetched live from the YouTube Data API (not stored on \`samples\` in the DB).`,
    `- **Suno:** \`sunoai\`, hashtags like \`#suno…\`, or whole-word \`suno\` (not a substring inside e.g. Italian *nessuno*).`,
    `- **AI:** ai-generated / made-with-AI phrasing, \`#aimusic\` / \`#aigenerated\`, \`suno ai\`, or \`artificial intelligence\` (excluding common upscale/Topaz-style restoration blurbs).`,
    ``,
    `---`,
    ``,
  ]

  if (matches.length === 0) {
    lines.push(`No matches.`)
  } else {
    matches.forEach((m, idx) => {
      const flags = [m.suno ? "suno" : null, m.ai ? "ai" : null].filter(Boolean).join(", ")
      lines.push(`## ${idx + 1}. ${m.title.replace(/\s+/g, " ").trim()}`)
      lines.push(``)
      lines.push(`- **Channel:** ${m.channel}`)
      lines.push(`- **YouTube ID:** \`${m.youtubeId}\``)
      lines.push(`- **URL:** https://www.youtube.com/watch?v=${m.youtubeId}`)
      lines.push(`- **Matched:** ${flags}`)
      lines.push(`- **Description excerpt:** ${m.excerpt}`)
      lines.push(``)
    })
  }

  fs.writeFileSync(OUT, lines.join("\n"), "utf8")
  console.log(`[scan-bio] Wrote ${matches.length} match(es) to ${path.resolve(OUT)}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
